numeric_cast.hpp: add missing include
Including cstdint is required by uintmax_t.

Fixes the following:

openvpn/common/numeric_cast.hpp:66:25: error: ‘uintmax_t’ does not name a type

Signed-off-by: Antonio Quartulli <antonio@openvpn.net>