exception: Make err string consistently "const std::string&"
Coverity complains (for every occurence of the macros...)
"C++ string which is never changed is passed by value rather than by reference"

Signed-off-by: Frank Lichtenheld <frank@lichtenheld.com>