test_cpu_time: fix unused variable
clang 13 complains:
test/unittests/test_cpu_time.cpp:110:16:
error: variable 'd' set but not used [-Werror,-Wunused-but-set-variable]
        double d=0;

Signed-off-by: Frank Lichtenheld <frank@lichtenheld.com>