Update lz4 version to 1.8.3
The deprecated macro of LZ4 1.8.0 breaks in newer LLVM/Clang version:

include/lz4.h:446:12: error: an attribute list cannot appear here

LZ4LIB_API LZ4_DEPRECATED("use LZ4_decompress_safe() instead") int
LZ4_uncompress_unknownOutputSize (const char* source, char* dest,
int isize, int maxOutputSize);

Using -DLZ4_DISABLE_DEPRECATE_WARNINGS allows including these headers
with modern LLVM/Clang version

The new lz4 version (1.8.3) fixes this problem.