linux/genl: Make function implementation static in header file
The ovpn_nla_get_uint() is implemented as a function in a header file
and not delcared as a static function.  This breaks building OpenVPN 3
Linux:

  /usr/bin/ld: src/netcfg/openvpn3-service-netcfg.p/netcfg-dco.cpp.o: in function `openvpn::ovpn_nla_get_uint(nlattr*)':
  .../../openvpn3-core/openvpn/tun/linux/client/genl.hpp:58: multiple definition of `openvpn::ovpn_nla_get_uint(nlattr*)'; \
   src/netcfg/openvpn3-service-netcfg.p/core-tunbuilder.cpp.o:.../../openvpn3-core/openvpn/tun/linux/client/genl.hpp:58: first defined here

Signed-off-by: David Sommerseth <dazo@eurephia.org>