ip/ping6: Use _WIN32, not _MSC_VER (to fix MinGW).
When compiling openvpn3 with MinGW, the build fails as follows:

    openvpn3/openvpn/ip/ping6.hpp:46:20: error: no member named 's6_addr16' in 'in6_addr'
          return addr->s6_addr16;
                 ~~~~  ^

This is because the code checks for _MSC_VER instead of _WIN32.

Signed-off-by: Jay Freeman (saurik) <saurik@saurik.com>