Revert "SSL: Allow TLS alerts for failed new connections"
This reverts commit 0c789b360f0578daaef891fd0ede57a5420717a4.

Some production servers ended up in a CPU-consuming loop where all
that was printed out was:

SSL_ERROR: OpenSSLContext::SSL::read_cleartext: BIO_read failed, cap=2576 status=-1

While reverting the commit mentioned does not address the root
cause of the failure, it should at least address the log flood.

Allowing the underlying SSL library to send out TLS alerts is then
either not feasible because of the ASIO infrastructure, or at
least requires a much deeper dive.

Signed-off-by: Razvan Cojocaru <razvan.cojocaru@openvpn.com>