Fix builds with GCC 4.8 compilers
When building on RHEL 7 using the stock compiler (gcc-4.8.5), compiler
errors like this one began to appear after commit 8a502f3b6143832:

    core/openvpn/tun/linux/client/tunsetup.hpp:61:11: error: conversion from ‘openvpn::ActionList*’ to non-scalar type ‘openvpn::ActionList::Ptr {aka openvpn::RCPtr<openvpn::ActionList>}’ requested
         class Setup : public TunBuilderSetup::Base
               ^
On GCC 8.2 (via devtoolset-8), this error did not occur at all.  This
looks like a compiler bug, as declaring an empty Setup() constructor
resolves this issue.  But we currently want to have GCC 4.8.5 compilers
functional, as it provides native RHEL-7 support without any use of
software collections.

Signed-off-by: David Sommerseth <davids@openvpn.net>